Klimatbyran/frontend

- src/components/company/Scope3Emissions.astro
- src/components/company/Scope3EmissionsCategory.astro
Fix #41
- Add Swedish titles for all scope 3 categories. Descriptions and icons for the new categories will be solved in the future, as part of #43  
- Only show the scope 3 categories that were reported.
- Prepare code to make it easier to add translations. Made most sense to do it properly right away.
> Use actual scope 3 emission categories

- src/components/company/Scope3Emissions.astro
Fix #89 
I added units to the Uppströms/Nedströms title sections because I believe it's more accurate to specify the unit in the "table head" (i.e., the "closest" title). Additionally, this placement looks better on smaller screens compared to including it in "X rapporterar Y / 15 kategorier:" (which was another placement option I considered).
> add unit to scope 3 categories up- and downstream

- src/components/company/CompanyEmissions.astro
- src/data/companyData.ts
@Greenheart started working on handling the edge case where a company reports scope 1 and 2 emissions combined. Still needs work but feel free to build on if it's useful or scrap otherwise :) I won't have more time today so wont have time to finish this before launch tomorrow.
fix #244
> add combined scope 1 and 2 type and copy

- Dockerfile
> Fix #247 - Omit devDependencies and use locked versions when installing

- Dockerfile
- package-lock.json
- package.json
- Copy files before `npm ci` to fix postinstall scripts during CI. This should include the `astro.config.ts` which seems to be required before we can install `astro` or some other dependency.
- Fix low impact security issue.
- Fix CI build by including all actual dependencies as part of the `dependencies`. Previously, some critical packages like `unplugin-icons` and the icon packs were incorrectly added as `devDependencies`. The strange thing is that this is the officially recommended way to install these packages as per the `unplugin-icons` README.
> Fix config for production build to include all dependencies

- src/components/company/CompanyEmissions.astro
- src/components/company/CompanyFacts.astro
Also ensure emission values show as grayed-out `-` if no real data has been reported for that data point.
fix #241
> Ensure the overall total is `null` if no actual emissions have been reported

- src/components/footer/Footer.astro
- src/components/footer/Socials.svelte
In the footer, updating the github link to point to the organisation page rather than a specific repository for both the socials icon and footer text. 
[Linked Issue](https://github.com/Klimatbyran/beta/issues/274)
No visual change, just a change to the link.
> [Fix] Update Github Link in Footer

- vite.config.ts
Include, instead of exclude, lucide-react in Vite config's optimizeDeps in order to fix blank page when run locally.
> Include lucide-react in Vite config's optimizeDeps

- k8s/base/ingress.yaml
- k8s/base/networkpolicy.yaml
- Align namespaces: Update ingress.yaml and networkpolicy.yaml to match the frontend and frontend-stage namespaces instead of klimatkollen.
- Ensure correct traffic routing: Modify networkpolicy.yaml selectors to correctly allow traffic between services within the intended namespace.
Hi think this is what is setting us back and not allow to view the latest staging branch commit on the frontend url
> Update Ingress and Network Policy to Use the Correct Namespace

- .github/workflows/ci.yml
- Seems like cmd npm run build fails during our image building process
- Lets delete cached dependencies and log our current versions
> Fix build process

- README.md
- vite.config.ts
- I think our current logic removes the suffix /api leading to calls to ex: api.klimatkollen.se/companies without the api part of the url. Easy fix, lets try it
> Fix proxy with api suffix

- src/components/companies/detail/CompanyOverview.tsx
- src/components/companies/list/CompanyCard.tsx
- We have reportUrl as string | null in the schema
- This means that we need to check in the frontend that we have it by using optional chaining
- Should fix bugg in staging
> Fix: add optional chaining to reportUrl

- src/pages/LandingPage.tsx
Quick fix for faulty company ranking. Reintroduce at a later stage with other values than emissions change percent last two years since ranking on that is misleading seing to how our data looks before historical gaps are filled.
I've added an issue related to this reintroduction: #431
> 418 Comment out company ranked list and change grid

- package-lock.json
- package.json
- src/lib/blog/blogPostsList.ts
- src/pages/InsightsPage.tsx
- src/routes.tsx
- The blogposts linked to the insights page 
- Now they go to the correct <BlogPostComponent> and current language is part of url
> [Fix]: Blogpost routing

- src/pages/MunicipalityDetailPage.tsx
Changed value on municipality detailed pages so bike lanes are displayed correctly (instead of showing value for electricVehiclePerChargePoints).
> FIX correct value for bike lane meters on detailed municipality page

- src/components/companies/detail/CustomTooltip.tsx
Reduced width on baseYear tooltip on mobile devices since the tooltip containing the baseYear info would clip out of frame on smaller devices.
After:
Closes #[[609](https://github.com/Klimatbyran/frontend/issues/609)]
> [609] Reduced width on baseYear tooltip on mobile devices

- src/pages/MunicipalityDetailPage.tsx
Calculation of EV growth to percent is now moved to backend thus removed from frontend.
See related PRs
https://github.com/Klimatbyran/klimatkollen-deprecated/pull/755
https://github.com/Klimatbyran/garbo/pull/752
> FIX remove percent calculation of EV growth from frontend

- src/pages/MunicipalitiesRankedPage.tsx
Users will now be redirected back to same view as they were on when going back from a municipality detailed page (graph/list, KPI).
Also cleanup and minor restyling.
Closes #623
> 623 add view mode for list/graph and kpi to municipalities

- src/hooks/useMunicipalityKPIs.ts
- src/locales/en/translation.json
- src/locales/sv/translation.json
Neeeded emissions change percent is removed from municipality ranking page in preparation for new emissions data, since roughly 110 municipalities have exhausted their carbon budgets making it impossible to rank bottom 5.
> Feat remove municipality ranking needed emissions percent

- src/pages/LandingPage.tsx
The division for the percent is no longer needed so removed the /100 on the Ranked List for the top municipalities on the landing page.
After:
> [fix] Update Municipality Ranked List

- src/components/RankedList.tsx
- src/pages/LandingPage.tsx
The font size was too big to fix within one row on small screen sizes, reduce the default size a bit and set a smaller breakpoint to switch to larger text.
Before:
After:
> [#614] Reduce font size to avoid overflow of randed lists

- package-lock.json
- package.json
- src/components/companies/list/CompanyCard.tsx
- tailwind.config.js
Use container queries to better control the company card. Container queries are still somewhat new but the fallback will be for users with older browsers to always see the layout where emissions and change rates are stacked.
Before:
After
Closes #[696]
> [#696] Fix company card layout through container queries

- src/components/companies/detail/history/EmissionsLineChart.tsx
- src/components/municipalities/MunicipalityEmissionsGraph.tsx
- src/utils/localizeUnit.ts
> ### ✨ What’s Changed?
Introduced a new compact version number formatting for the emissions so that the Y axis labels take less space, and thus the graph can take more estate on mobile screen sizes.
Before: 
After:
Closes #689
> #689 Use compact numbers in historical emissions charts Y axis

- src/components/municipalities/list/MunicipalityCard.tsx
Change colors for emissions last year as well as historic change percent to match rest of site.
Before
After
> FIX change municipality card KPI colors to match rest of site

- src/components/companies/detail/Scope3Data.tsx
- src/lib/calculations/emissions.ts
- src/locales/en/translation.json
- src/locales/sv/translation.json
- src/pages/EmissionsTestPage.tsx
Fixed misspelled key "vizualization" to "visualization" in the English translation file. This was causing English locale to show Swedish text ("Visualisering") on company details pages.
Closes #768
> [768] Fix misspelled key 'visualization' in English locale

- src/components/companies/edit/CompanyEditRow.tsx
- src/pages/CompanyEditPage.tsx
Adapted company editor to cases where there's too many reporting periods too fit on the screen, with set column widths and horizontal scroll.
Before
After
> [fix] adapt company editor to overflowing reporting periods

- src/hooks/useValidationReports.ts
- src/pages/ValidationDashboard.tsx
Allowing for companies to have serveral linked issues on the validation dashboard.
Before
After
> [fix] allow for several issues to be shown per company on the validation dashboard

- src/components/layout/Header.tsx
This puts the reports at the top of the insights menu as discussed during weekly meeting.
> [fix] Reorder insights menu

- src/pages/LandingPage.tsx
* Make all cards on landing page have same margins left and right on mobile
* Minor cleanup of outcommented code
Before
After
> [fix] Make all cards on landing page have same margins left and right on mobile

- src/components/municipalities/map/SwedenMap.tsx
- src/components/municipalities/rankedList/KPIDetailsPanel.tsx
- src/components/municipalities/rankedList/MunicipalityInsightsList.tsx
- src/components/municipalities/rankedList/MunicipalityInsightsPanel.tsx
- src/components/municipalities/rankedList/MunicipalityRankedList.tsx
- src/locales/en/translation.json
- src/locales/sv/translation.json
- src/types/municipality.ts
I made sure that municipalities with null or undefined values for a given KPI are sorted last in the rankings on the map and in the insight panel.
Closes #[806]
> [806] Handle null values in municipality rankings

- src/data-guide/ProgressiveDataGuide.tsx
- src/data-guide/ProgressiveDataGuideMobile.tsx
- src/data-guide/SectionWithHelp.tsx
- src/locales/sv/translation.json
Added paddings to detailed company and municipality cards.
Also minor tweaks in alignment of items in cards as well as a suggestion for Swedish button copy.
Before
After
Closes #928
> [928] restyle data guide

- src/components/layout/ContentCard.tsx
- src/lib/blog/blogPostsList.ts
- src/lib/constants/reports.ts
- src/locales/en/translation.json
- src/locales/sv/translation.json
- src/pages/BlogDetailPage.tsx
- src/pages/InsightsPage.tsx
- src/pages/ReportsPage.tsx
- src/types/content.ts
The category and language labels in report and article pages (both the list and the individual articles) have been translated to the selected language of the website. Dates used on those pages are also localized.
Before:
After:
> [916] Translate category and language labels and localize dates for article and report

- src/components/layout/ContentCard.tsx
Changes to prevent report card labels to overflow parent div on small screens
Before
After
Closes #960
> [960] prevent labels from overflowing report card

- public/reports/2024-06-Bolagsklimatkollen/index.html
- src/lib/constants/reports.ts
While the report analyse data from 2023, the report itself is the Klimatkollen 2024 report.
Update last years report to be named "Bolagsklimatkollen 2024" to be inline with the 2025 report as suggested on Discord.
> [fix] Change name of 2024 report to match 2025 report

- src/components/layout/Header.tsx
- src/components/newsletters/NewsletterNavigation.tsx
- src/components/ui/pagination.tsx
- src/locales/en/translation.json
- src/locales/sv/translation.json
- src/pages/NewslettersPage.tsx
Per change request from Ola, the following changes has been made in this pr:
- Newsletter Archive link moved from Insights nav to About us nav
- Changed translation text for the header subscribe button to "Join Newsletter" in English, and "Prenumerera på nyhetsbrev" in Swedish. Do differentiate from the newsletter archive site. 
- Added the header's "Subscribe to newsletter" button to the newsletter archive page below the navigation, but only visible on mobile.
- Switched newsletter navigation buttons to say "Previous & Next" in English, and "Föregående & Nästa" in Swedish.
New button:
New translations Newsletter nav:
New translations header subscribe button:
Closes #965
> [965] Change to subscribe button translations, added button to newsletterpage

- src/components/companies/detail/history/EmissionsHistory.tsx
Hide trend explanation from company emissions graph for now as it seems lite different trend calcs arent being used (and are a bit too premature to be released)
> [fix] hide trend explanation from company emissions graph for now

- src/components/companies/detail/history/EmissionsLineChart.tsx
* Make company emissions scope and sector line graphs appear again
* Align active dots of different data views
Before
After
> [fix] make comapny scope and sector line graphs appear again

- src/components/municipalities/emissionsGraph/OverviewChart.tsx
- src/components/municipalities/emissionsGraph/SectorsChart.tsx
Adjusted left margin of Y-axis to counter the clipping of Y-axis values. 
Before:
After:
Closes #1020
> [1020] Adjusted left margin to counter legend clipping

- src/components/LocalizedLink.tsx
- src/components/RankedList.tsx
- src/components/companies/list/CompanyCard.tsx
- src/components/layout/Header.tsx
- src/components/municipalities/list/MunicipalityCard.tsx
- src/components/municipalities/rankedList/MunicipalityInsightsList.tsx
Using LocalizedLink takes into account which language the user is using. This way we can centralize the logic to add the path prefix instead of spreading out it in different places.
There are a couple of places where we use buttons or click handlers to navigate that we should replace with links which also fixes accessibility issues of using custom navigation.
This was noticed due to problems with #918 where the current implementation does not support the non-languaged URLs.
> [fix] Add LocalizedLink to replace Link

- package-lock.json
This seems to have been removed from the package-lock file in #1064 which breaks running the project on non-mac machines.
`npm run dev` on a linux machine pointed at https://github.com/npm/cli/issues/4828
> [fix] Readd optional platform specific dependencies

- src/components/relatableNumbers.tsx
- src/data-guide/SectionWithHelp.tsx
- src/index.css
As we needed more space horizontally the x padding was reduced but not the y padding which made the cards look unaligned.
This makes the padding match better and also introduce a new level of rounded that we can use on small devices.
Before Desktop:
After Desktop:
Before Mobile:
After Mobile:
> [fix] Improve padding in section cards

- src/components/pageStates/Error.tsx
- src/components/pageStates/Loading.tsx
- src/components/pageStates/NoData.tsx
- src/locales/en/translation.json
- src/locales/sv/translation.json
- src/pages/CompanyDetailPage.tsx
- src/pages/MunicipalityDetailPage.tsx
Extract these components from the company detail page and reuse them in the municipality detail page.
At some point it would be nice to go over these to ensure they look better but they aren't heavily used as we fetch and cache all companies and municipalities on load.
> [fix] Extract loading, error and no data components
