src/components/company/CompanyEmissions.astro
src/components/company/CompanyFacts.astro
src/components/company/Scope3Emissions.astro
src/components/company/ScopeEmissions.astro

Add biogenic emissions

---

src/components/company/OtherCompanies.svelte
src/components/ui/combobox/combobox.svelte

Allow combobox width to be customized and add overflow ellipsis for long names

---

src/components/ui/combobox/combobox.svelte

Better solution would be to limit rendering using JS, but let's save that for another time
Progress towards #50

Only show top 5 results in combobox using CSS

---

src/components/company/Company.astro
src/components/company/Scope3Emissions.astro
src/data/companyData.ts

Fix/hide category 16 since we don't want to show it

---

src/components/company/Scope3Emissions.astro

Show reported categories as upstream and downstream

---

src/components/company/Company.astro

update email from hej to data

---

src/components/company/CompanyEmissions.astro
src/components/company/CompanyFacts.astro
src/components/company/Scope3Emissions.astro

Remove fraction digits from numbers

---

src/components/company/CompanyGoals.astro
src/components/company/CompanyInitiatives.astro

fix: left align headers

---

src/components/company/CompanyFacts.astro
src/data/companyData.ts

Fix-146 type errors likely causing 146

---

src/components/company/Scope3EmissionsCategory.astro

Added a class to fix the bug.
Fixes #165

Add class "w-full" to Scope3EmissionsCategory component

---

src/components/company/CompanyEmissions.astro

Change phrasing for utsläpp to rapporterade utsläpp

---

src/components/company/CompanyEmissions.astro
src/components/company/CompanyFacts.astro
src/data/companyData.ts

Improve calculation for total emissions

---

src/pages/foretag/[id].astro

Add page title

---

src/components/company/OtherCompanies.svelte

Fix #160 to improve UX when navigating between pages

Fix navigation in combobox to force page reload when selecting a list item

---

src/components/company/CompanyGoals.astro

CompanyGoals: Hide details if year is missing

---

k8s/api.yaml
src/components/company/Company.astro
src/components/company/CompanyEmissions.astro
src/components/company/CompanyFacts.astro

Some changes are duplicates due to how they were merged.

New frontend production build

---

src/components/company/Scope3Emissions.astro
src/components/company/Scope3EmissionsCategory.astro

- Fix formatting error for scope 3 categories

Release to production

---

Dockerfile
src/components/company/Scope3Emissions.astro

- Fix #212 - Update copy for scope 3 categories
- Fix: Always show scope 3 categories even when no values have been reported
- Fix #247 - Omit devDependencies and use locked versions when installing

Update production for frontend

---

src/components/company/CompanyEmissions.astro

fix #255 - Hide scope 3 total if no data reported

---

Dockerfile
package-lock.json
package.json
src/components/company/CompanyEmissions.astro
src/components/company/CompanyFacts.astro
src/data/companyData.ts

Including several key fixes to cover more edge-cases with the data. This makes the data look much more correct compared to before.
Unfortunate to have to add so many conditions, but this is the probably just the reality of this dataset.

Deploy frontend to production

---

src/components/company/CompanyFacts.astro

- Refine condition for hiding total emissions when no valid data is available

Update frontend production

---

src/components/company/CompanyFacts.astro

Fix #262 - Show statedTotalEmissions if verified and nothing else reported

---

src/components/company/CompanyEmissions.astro
src/components/company/CompanyFacts.astro

- Fix #262 - Show statedTotalEmissions if verified and nothing else reported
- Ensure biogenic emissions are grayed out if no data was provided

Release frontend to production

---

src/components/company/Company.astro
src/components/company/CompanyEmissions.astro
src/components/company/CompanyFacts.astro
src/components/company/Scope3Emissions.astro

Show company details page even if a reporting period is missing `emissions` or `economy`

---

package-lock.json
package.json
scripts/generate-api.js
src/lib/api-types.ts

Use http://localhost:3000/api/openapi.json in development instead of api.klimatkollen.se. Makes development workflow smoother when the external API is unavailable.

fix for generating api types locally when running in DEV

---

src/components/layout/Footer.tsx

Also hardcode copy email button's width. If you know more elegant ways of doing this, please leave as comment :)

Stack footer email and copy button on smaller screens

---

src/components/ContentBlock.tsx
src/components/RankedList.tsx
src/pages/LandingPage.tsx

Solve #344 
Landing page is adapted to mobile screens, also some restyling on larger screens. Commented out extended KPI top list for municipalities.

Adapt landing page to mobile screens

---

src/components/municipalities/MunicipalityEmissionsGraph.tsx
src/components/municipalities/MunicipalityLinkCard.tsx
src/components/municipalities/MunicipalitySection.tsx
src/components/municipalities/MunicipalityStatCard.tsx
src/pages/MunicipalityDetailPage.tsx

* Edit styling of detailed municipality page to fit mobile screens
* Break out reusable components from municipality detailed page
* Edit graph (legends) to fit mobile screens

Review detailed municipality view

---

README.md

Removed all references to Astro and Svelte, added (minor) explaination of current project structure and new tech stack.

Update readme to reflect new tech stack

---

.github/workflows/ci.yml
README.md

- Restoring ci.yaml 
- After a pipeline session last week there was some leftover code in the ci file, this could get confusing so this restores it to a more correct version

Cleanup ci job

---

src/lib/constants/urls.js

Added URL to staging API and introduced it as a case for base URL

Make staging use staging API

---

README.md
vite.config.ts

- Fix was wrong, baseUrl already adds the api, part, removing dupllicate api in url

Revert incorrect proxy url

---

README.md
k8s/overlays/production/kustomization.yaml
k8s/overlays/production/nginx-config-patch.yaml
vite.config.ts

- Nginx had a hardcoded proxy pass to our production api.
Fixed this and added a patch for production so that is correct

Fix nginx for production and staging

---

k8s/base/deployment.yaml
k8s/overlays/production/deployment-patch.yaml
k8s/overlays/production/kustomization.yaml
src/contexts/AuthContext.tsx

In order to be able to log in in all environments we need a dynamic client id

[Fix] Dynamic client id for different environments

---

src/i18n.js

Make swedish default language of site, since a lot of Swedes have English as system language and we're still predominantly focused on Swedish users.

417 Make swedish default language

---

src/locales/sv/translation.json
src/pages/MethodsPage.tsx

429 reintroduce links to co2budgets on methods page

---

README.md
k8s/overlays/production/ingress-patch.yaml

Noticed that the ingress failed, seems like we where missing a target namespace

Update namespace for production

---

README.md
k8s/base/ingress.yaml
k8s/overlays/production/ingress-patch.yaml

- The final namespaces are set in the kustomizatin.yaml
- So setting them in the ingresses as well was causing build fails
- Fixed

[FIX] ingress namespaces

---

src/components/MembersGrid.tsx
src/components/TeamMember.tsx
src/components/layout/AccordionGroup.tsx
src/pages/AboutPage.tsx

Break out component for team and board, so that styling is consistent (according to feedback from @Klimatkollen ). Also restyle about page to better fit mobile screens.
Solve #427

427 Adapt about us team and board memebers to mobile

---

src/components/municipalities/list/MunicipalityCard.tsx
src/components/municipalities/list/MunicipalityCardInfo.tsx

Fix issue with funky alignment of emissions data on municipality cards on mobile screens and break out reusable component to present said data.
Solve #430

430 fix alignment issues on muni card and break out component

---

package-lock.json

Deleted and regenerated the package-lock.json file in order to fix failing builds in the pipeline.

[FIX] Regenerate lock file

---

README.md

* Add more context about the project
* Updates to localhost
* Add info on how to run locally

CHORE update readme

---

src/locales/en/translation.json
src/locales/sv/translation.json
src/pages/MethodsPage.tsx

Add new section about our calculations (to be expanded later) and info about our approximated municipality emissions as well as example calculation for municipality emissions kpi:s.
Solve #527

527 add methodology section about our calculations

---

src/components/ui/typewriter.tsx

Added catches for potentially empty strings.
Also some formatting, with added ; where there were none

FIX bug in production where site crashes due to trying to get length of undefined

---

package-lock.json
package.json

* fix for bug in typewriter component that crashed site

Release to prod new patch version 3.7.7

---

src/components/municipalities/MunicipalityEmissionsGraph.tsx
src/pages/MunicipalityDetailPage.tsx

- Move municipality line graph legend to bottom instead of top
- Add correct string to no Paris path graph scenario
Closes #681

681 Move municipality line graph legend

---

src/pages/MunicipalityDetailPage.tsx

Add conditional coloring of needed emissions change depending on if municipality meets paris agreement
Closes #715

715 conditional coloring of municipality needed emissions percent

---

src/pages/MunicipalityDetailPage.tsx

Add conditional coloring of municipality EVs per public charging point, based on old EU KPI CPEV (10 EVs per public charging point).
Closes #717

717 add conditional coloring of municipality EVCP

---

package-lock.json
package.json
src/components/companies/edit/CompanyEditScope1.tsx
src/components/companies/edit/CompanyEditScope3.tsx
src/lib/company-edit.ts

Quick fix to solve issue in saving process in the editor

Fix editor not saving

---

src/pages/MunicipalityDetailPage.tsx

Remove duplicate municipality sector emissions pie chart (only keep version with year selector).

[fix] remove duplicate municipality sector emissions pie chart

---

src/locales/en/translation.json
src/locales/sv/translation.json

Update strings to reflect new data entry for 2022 for municipality consumption emissions
Closes #581

[581] update consumption emissions strings

---

src/hooks/useValidationClaims.ts
src/hooks/useValidationReports.ts
src/lib/api-types.ts
src/lib/api.ts
src/pages/ValidationDashboard.tsx

Add support for claiming validations and show and report issues to the Validation Dashboard.

[feat] Validation claims & reports

---

src/locales/sv/translation.json

Updated link for municipality bike lane data source.
Closes #799

[799] update link for municipality bike lane data

---

src/locales/en/translation.json

Update eng translation file with correct link to NVDB, since this was missed in #803

[fix] update English link to municipality bike lane data

---

src/hooks/useVerificationStatus.ts

companies dissappeared from the verification dashboard even though their scope3 total amount was not verified. this is a fix for that
- [ x] PR title starts with [#issue-number]; if no issue is applicable use: [fix], [feat], [prod], or [copy]
- [ x] I've verified the change runs locally
- [ x] I've set the labels, issue, and milestone for the PR

adding check for verification of scope 3 total too, not just categories

---

src/components/companies/sectors/charts/SectorEmissionsChart.tsx
src/components/graphs/BarChart.tsx

For the company bar chart, decrease axis font sizes, move y axis unit and remove grid to make more room for the chart and align with other charts on site.
Before
After

[fix] restyle company bar chart

---

src/data-guide/DataGuideMarkdown.tsx

Indent the text a bit and adjust max width to upper bounds of recommendation for text readability.

[fix] Tweak text width and padding on data guide items

---

src/locales/sv/translation.json

Updated after Olas suggestions.

Improve swedish Data Guide translations

---

src/components/methods/content/SourcesContent.tsx
src/hooks/useMunicipalityKPIs.ts
src/locales/en/translation.json
src/locales/sv/translation.json

Correct source link for municipality charging point data
Also minor cleanup

[fix] correct municipality charging point source link

---

src/components/layout/Header.tsx
src/components/search/HeaderSearchButton.tsx
src/components/search/SearchDialog.tsx
src/locales/en/translation.json
src/locales/sv/translation.json

Move the search button towards the right hand of the main menu and reduce the size a bit by moving the shortcut hint into the dialog instead of having it in the button. The shortcut is more of a power user feature that allows for improved workflow once you know it.
**Before**
**After**

[fix] Tweak the search header search button

---

src/components/search/HeaderSearchButton.tsx

Feedback from UX to make the search icon white to make it look more enabled.
Before:
After:

[fix] Make the search button look less disabled

---

src/components/companies/detail/emissions-assessment/EmissionsAssessmentButton.tsx
src/components/companies/detail/emissions-assessment/EmissionsAssessmentDialog.tsx
src/components/companies/detail/emissions-assessment/YearSelectionModal.tsx
src/components/companies/edit/test/editor-logic.test.tsx
src/components/companies/sectors/trends/TrendCard.tsx
src/components/companies/sectors/trends/TrendCards.tsx
src/components/companies/sectors/trends/TrendCompanyList.tsx
src/components/layout/InfoTooltip.tsx
src/components/layout/Selector.tsx
src/components/methods/content/CompanyDataOverview.tsx
src/components/methods/content/DataCollectionProcess.tsx
src/components/methods/content/EmissionsCategories.tsx
src/components/methods/content/HistoricalData.tsx
src/components/municipalities/MunicipalityStatCard.tsx
src/components/products/DownloadCard.tsx
src/components/products/DownloadControls.tsx
src/data-guide/ProgressiveDataGuideMobile.tsx
src/pages/SupportPage.tsx

Since we don't enforce it in CI yet there are bound to be some issues not cought. This runs prettier on all files and correct the ones that don't follow the formatting.
`npx prettier -w **/*.ts[x]`

[chore] Run prettier on the code

---

src/locales/sv/translation.json

Change utsläpps to utsläpp in copy.

Utsläpps -> utsläpp (copy)

---

src/components/companies/list/CompanyCard.tsx

Added an absolute positioning to the AI-icon and it's parent on companyCard to prevent it from taking space and also shifting the positioning of the text. Also moved the AI-icon abit further up.
Before:
After:
Closes #951

[951] Misalignment of emissions and emissions change values on company cards

---

src/pages/ReportLandingPage.tsx

Minor error fixes in report landing page. Came across and fixed them while working on a bug.

[bug] minor error fixes in report landing page

---

src/components/companies/detail/overview/CompanyOverview.tsx

Swapped places on the conditional emissions unit display so that it actually displays when there's a value.

[Fix] Switched placed on conditional unit display

---

package-lock.json
package.json

* Update i18next
* Run install

[chore] update deps

---

package-lock.json
package.json

> **Title format:** `[Prod] Major/Minor/Patch Version Bump vX.X.X`
_Select the appropriate release type by marking with an `x`._
_Note the relevant rollback version to enable quick rollback if necessary._
v4.6.5 (v4.7.0 not stable)
This release promotes changes **from `stage` to `production`**.
_Provide a summary of the features, fixes, or updates included in this production release._
- Merge of pie chart tooltips into one component
- Update and fix of deps and packages
---
_This template is for versioned production releases only. For other PR types, please select a different template._

[Prod] Patch Version Bump v4.7.1

---

src/components/companies/detail/history/ChartHeader.tsx

Hide data selector from company emissions chart header since scope and sector graphs have bugs that need fixing.

[fix] hide data selector from company emissions chart header

---

src/hooks/useBoardMembers.ts

[fix] correct madeleines surname

---

src/components/companies/detail/history/EmissionsHistory.tsx
src/locales/dataguide/en/baseYear.md
src/locales/en/dataguideItems.json

Display the base year help in emissions history section.

[fix] Add baseyear help

---

src/components/RankedList.tsx
src/components/layout/Header.tsx
src/pages/LandingPage.tsx
src/routes.tsx

Added linking from the top list headings on the landing page to the municipality top lists and company graphs.
Closes #705

[705] Added linking from landing top lists to municipality and companies

---

src/components/methods/MethodNavigation.tsx
src/pages/MethodsPage.tsx

Navigation in methodology page was broken, so user had to click section two times to see it (clicking one time only changed the URL). Now fixed!

[Fix] broken methodology navigation

---

src/components/methods/content/CarbonLaw.tsx
src/locales/sv/translation.json

Update of Swedish carbon law copy.
Closes #1007

[1007] update swedish carbon law copy

---

package-lock.json
package.json

> **Title format:** `[Prod] Major/Minor/Patch Version Bump vX.X.X`
_Select the appropriate release type by marking with an `x`._
_Note the relevant rollback version to enable quick rollback if necessary._
v4.7.3
This release promotes changes **from `stage` to `production`**.
_Provide a summary of the features, fixes, or updates included in this production release._
- add new municipality data: Carbon Law, LAD trend, update unit to CO2e
- add Our Approach to About
- bug fixes
---
_This template is for versioned production releases only. For other PR types, please select a different template._

[Prod] Prod Major Release 5.0.0

---

src/hooks/municipalities/useMunicipalitySectors.ts
src/locales/en/translation.json
src/locales/sv/translation.json

Add new translations for municipality sectors. Will hopefully simplify work with municipality sector line graph legends.

[fix] rename municipality sectors

---

package-lock.json
package.json

upgraded vite due to a vulnerability, and ran audit fix to fix some other deps
- [ x] PR title starts with [#issue-number]; if no issue is applicable use: [fix], [feat], [prod], or [copy]
- [ x] I've verified the change runs locally both on mobile and desktop

[fix] upgraded vite and ran audit fix

---

Dockerfile

This pull request introduces a security check to the Docker build process by running an automated vulnerability audit before installing dependencies.
Security improvements:
* Added a `RUN npm audit` step to the `Dockerfile` to check for vulnerabilities in dependencies before installation.

fix: auto audit before running npm i

---

src/components/LocalizedLink.tsx
src/components/layout/Header.tsx
src/components/ui/navigation-menu.tsx

Migrate the main navigation from Radix Menubar to NavigationMenu which provides better keyboard navigation for our use case as Menubar is designed for an application menu (File, Edit, ...) in a desktop application rather than the main navigation for a web site that we are using it for.
I also had to make some changes to our wrapper around the Radix components as they put the sub menu in the wrong place and didn't fit our look & feel fully.
Before:
After:
Fixed #971

[971] Main menu navigationmenu

---

src/locales/sv/translation.json

[fix] minor typo in emissions history swe translations
